apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinelguard-data
  labels:
    app.kubernetes.io/name: sentinelguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
